#! /usr/bin/env sh

# pkdocs
# Pack up the html documentation for the vidprofile suite

HTML_TAR="vidprofile-html-docs.tar"
HTML_GZ="vidprofile-html-docs.tar.gz"
HTML_DIR="html"

T2T_TAR="vidprofile-t2t-docs.tar"
T2T_GZ="vidprofile-t2t-docs.tar.gz"
T2T_DIR="src"

PKDOCS_PWD=`pwd`

$PKDOCS_PWD/mkdocs

echo
echo "Packing html files..."
echo

cd $PKDOCS_PWD/$HTML_DIR

rm -fv $HTML_GZ
tar -cvvf $HTML_TAR *.html *.php *.css fig/*
gzip -v $HTML_TAR
rm -fv $HTML_TAR

echo
echo "Packing t2t files..."
echo

cd $PKDOCS_PWD/$T2T_DIR

rm -fv $T2T_GZ
tar -cvvf $T2T_TAR *.t2t *.html
gzip -v $T2T_TAR
rm -fv $T2T_TAR
mv -v $T2T_GZ $PKDOCS_PWD/$HTML_DIR

echo
