#! /usr/bin/env sh

# Pack up the html documentation for the vidprofile suite

DOC_TAR="html-docs.tar"
DOC_GZ="vidprofile-html-docs.tar.gz"

rm -fv $DOC_GZ

`pwd`/mkdocs

tar -cvvf $DOC_TAR *.html *.css fig/*
gzip -v $DOC_TAR

rm -fv $DOC_TAR